# Generated by Django 4.1.6 on 2023-02-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_school_data_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_data',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student_school_data',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='student_school_data',
            name='Commute',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
