# Generated by Django 4.1.6 on 2023-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_data_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_school_data',
            name='Commute',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
